<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hi, Cado Admin</name>
   <tag></tag>
   <elementGuidId>5ee1c361-8e3e-4f1b-8f87-da994187ac7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dashboard-header-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_drawer_example_basic_button']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d21e1865-9307-4a6b-aa79-38e15dd3aef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-header-btn</value>
      <webElementGuid>0e54aded-ca4c-4cd0-9d7d-31f6fcad93e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi, Cado Admin</value>
      <webElementGuid>b11d2c74-8370-4712-a614-a2fca946be64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_drawer_example_basic_button&quot;)/button[@class=&quot;dashboard-header-btn&quot;]</value>
      <webElementGuid>ad195bed-9193-48f2-b769-7d6d6cab0002</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_drawer_example_basic_button']/button</value>
      <webElementGuid>8fcf7aa8-263a-472d-8598-603e60510683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::button[1]</value>
      <webElementGuid>443d856e-d090-4450-b6b4-c31d7b4026fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nextsix Listing'])[1]/following::button[1]</value>
      <webElementGuid>2fa639b4-6573-472b-96e9-513d227939c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[2]/preceding::button[1]</value>
      <webElementGuid>0b329ff3-0aa1-4260-ad6d-9406134f6261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Room'])[2]/preceding::button[1]</value>
      <webElementGuid>2f20fa79-c3d5-44f2-93f5-0438de50a494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hi,']/parent::*</value>
      <webElementGuid>e1beea06-9bf0-4c71-b4d2-fb728166dbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/button</value>
      <webElementGuid>e18938d1-62e3-465b-85ee-90d6affaaf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Hi, Cado Admin' or . = 'Hi, Cado Admin')]</value>
      <webElementGuid>f5e689c7-4dd8-404f-89e0-0d7b90fbb35f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
