<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Profile</name>
   <tag></tag>
   <elementGuidId>d09c271d-b53b-48ef-8d4a-1b0a1bb1aa77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-my-profile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_drawer_example_basic']/div/div/div/button/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>579a0b9b-09fb-4273-837a-4e89fdd0ff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-my-profile</value>
      <webElementGuid>4d5be296-287b-43f0-84da-723347a3f355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Profile</value>
      <webElementGuid>52df88b2-9d95-43a9-b359-22a829bd1d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_drawer_example_basic&quot;)/div[1]/div[1]/div[@class=&quot;right-sidebar-item-container&quot;]/button[@class=&quot;btn btn-active-light-dark sidebar-btn&quot;]/div[@class=&quot;right-sidebar-btn-text&quot;]/div[@class=&quot;btn-my-profile&quot;]</value>
      <webElementGuid>daec8d87-3cb0-4442-b690-00fcdf10d23d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_drawer_example_basic']/div/div/div/button/div/div</value>
      <webElementGuid>a66235a7-d86f-4940-bc57-c11ec643259e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::div[3]</value>
      <webElementGuid>720c2382-3767-40d0-b136-8289a7caf990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cado Admin'])[1]/following::div[3]</value>
      <webElementGuid>257a2622-b22b-4f52-99a7-180b5efad013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit personal or company info'])[1]/preceding::div[1]</value>
      <webElementGuid>76adf29e-470f-4aaf-994f-d77bec6617fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::div[2]</value>
      <webElementGuid>a9ab684c-8f66-4551-9fc4-0e3c099e927b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Profile']/parent::*</value>
      <webElementGuid>50686b7b-2a67-40fc-90b6-4fed9fe9d288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div</value>
      <webElementGuid>ec6575af-6753-4a5f-8ffa-3210b122d0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'My Profile' or . = 'My Profile')]</value>
      <webElementGuid>f30f3194-652c-4128-829b-88e626304669</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
