<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Undo_ifmail</name>
   <tag></tag>
   <elementGuidId>2d0267e4-38be-4567-8016-b6bcbd5981c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>58d4cb7e-38a0-4ba1-a8d9-fff6bde5254c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifmail</value>
      <webElementGuid>a45e3294-d734-41b5-8fed-9a8971391665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>onloadifmail()</value>
      <webElementGuid>a9dad56b-e3c2-4c22-85a0-35721967322d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifmail</value>
      <webElementGuid>161e52e1-116c-4f08-a568-ad24a6403219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>609db9d1-f081-41c9-9eb0-5e0ed7b60bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifmail&quot;)</value>
      <webElementGuid>8a0d6b71-dbe1-48c9-ab18-12c4b6202564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifmail']</value>
      <webElementGuid>f13c0ba1-b928-4883-b072-ff948b6231df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wmmailmain']/iframe</value>
      <webElementGuid>0fbdb2fc-e071-4e15-acb2-1cad2c67a527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/iframe</value>
      <webElementGuid>ddc701c0-8ff7-424a-8d59-332c3168b2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'ifmail' and @id = 'ifmail']</value>
      <webElementGuid>1f7f12cb-e264-4214-9c9f-891f8a58cdb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
