<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repeat New Password_repeatNewPassword</name>
   <tag></tag>
   <elementGuidId>5d603fed-9a22-4635-9e02-cd39e85fb8f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;repeatNewPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='repeatNewPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>716a68c5-0bb1-4131-bfad-0f6d85bc9c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0ca4edb9-1185-4792-ad46-28709129e977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control personal-input-edit</value>
      <webElementGuid>c18b040f-d22a-412f-839a-a41f3523a39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Repeat New Password</value>
      <webElementGuid>6208a17d-2044-4e52-a756-aa7c395862e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatNewPassword</value>
      <webElementGuid>cecd0090-b14d-46b0-ad2d-5a086651836e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;profile-container&quot;]/form[@class=&quot;card card-custom card-shadow card-profile-right&quot;]/div[@class=&quot;card-body&quot;]/div[2]/div[@class=&quot;profile-change-password-input&quot;]/div[@class=&quot;profile-change-password-formik&quot;]/input[@class=&quot;form-control personal-input-edit&quot;]</value>
      <webElementGuid>53987749-98e5-4acf-a04b-4871b475d18b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='repeatNewPassword']</value>
      <webElementGuid>1cd9faa6-6fdd-4983-baf9-5a530302a9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/form/div/div[2]/div[3]/div/input</value>
      <webElementGuid>65617ade-aba4-4de6-b4b8-89e532097297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>b41b0930-a77f-49e1-a780-8a5f76483741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Repeat New Password' and @name = 'repeatNewPassword']</value>
      <webElementGuid>2e25defb-0fde-46c5-9070-f1e40095d92a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
