<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Old Password_oldPassword</name>
   <tag></tag>
   <elementGuidId>64872dbf-bf00-426a-832a-1b1cb1b6865f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;oldPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='oldPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1c64343-6aed-48d8-a98a-398525159730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f5b739b3-2285-4442-886c-b5e8f087caa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control personal-input-edit</value>
      <webElementGuid>fe2f2000-6fa4-43ed-9125-4193dc748267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Old Password</value>
      <webElementGuid>b9340fc6-44d8-4cd0-8566-47b10d829fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>oldPassword</value>
      <webElementGuid>a5047d8f-6e85-46a5-ab1c-0a1303febaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;profile-container&quot;]/form[@class=&quot;card card-custom card-shadow card-profile-right&quot;]/div[@class=&quot;card-body&quot;]/div[2]/div[@class=&quot;profile-change-password-input&quot;]/div[@class=&quot;profile-change-password-formik&quot;]/input[@class=&quot;form-control personal-input-edit&quot;]</value>
      <webElementGuid>03345f77-dd2f-4b0b-9365-17ed141fbeb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='oldPassword']</value>
      <webElementGuid>d185b846-a314-49b4-9cf7-877c3d122318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/div/form/div/div[2]/div/div/input</value>
      <webElementGuid>83e4df44-059f-41a7-9ce4-012164b109d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>979492da-3e4a-4628-981f-c45b77557abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Old Password' and @name = 'oldPassword']</value>
      <webElementGuid>0a117c1e-96b3-42bd-b734-967cd56a0b8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
