<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sit-admin.iroomz.comreset-password28c7_68ce87</name>
   <tag></tag>
   <elementGuidId>136b3291-5787-4dc9-bcb0-18c3fa9a8707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mail > div > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78d00796-f93b-4ec0-ab30-b4881a87462b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sit-admin.iroomz.com/reset-password/28c786038d09b89b4eea95ce9b0290ab0195616fbff7794f8823dc7935f26b40</value>
      <webElementGuid>d92cda88-665a-4b6d-8ab6-91d7dcdbc6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/span[1]</value>
      <webElementGuid>33909772-a769-4f03-88b2-ce9c2b7ad6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/iframe_Undo_ifmail</value>
      <webElementGuid>a0f43890-44c0-47a0-80e8-d77ee72c9aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/span</value>
      <webElementGuid>874e3a19-f917-4596-9b48-a312c868f97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Having trouble?'])[1]/following::span[1]</value>
      <webElementGuid>4f6a19f0-bca5-4f47-b9dd-99c651b9f872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[1]/following::span[1]</value>
      <webElementGuid>144617bc-b54f-47c7-a889-48cb659b268c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='sit-admin.iroomz.com/reset-password/28c786038d09b89b4eea95ce9b0290ab0195616fbff7794f8823dc7935f26b40']/parent::*</value>
      <webElementGuid>acd9aec3-a905-4457-96a4-64c01da491a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>13d5f08f-3cf4-431b-9192-c5576470029f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'sit-admin.iroomz.com/reset-password/28c786038d09b89b4eea95ce9b0290ab0195616fbff7794f8823dc7935f26b40' or . = 'sit-admin.iroomz.com/reset-password/28c786038d09b89b4eea95ce9b0290ab0195616fbff7794f8823dc7935f26b40')]</value>
      <webElementGuid>a04d31a9-6c60-4510-becf-40f5dbbfd85c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
