<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NextSix</name>
   <tag></tag>
   <elementGuidId>66b6e556-a050-4d01-ae89-9365c2fbd243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lmf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_ZwLjZmZkZQLlAwV3ZQNjAGZ3BQx4Zt==']/button/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>82386f93-5c82-4ad4-b5c4-d2e5acfad383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lmf</value>
      <webElementGuid>6ed979e9-db88-4128-8ef9-549a77fe070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NextSix</value>
      <webElementGuid>20b14fef-de65-49f0-b7f8-1941bd9e0c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_ZwLjZmZkZQLlAwV3ZQNjAGZ3BQx4Zt==&quot;)/button[@class=&quot;lm&quot;]/div[@class=&quot;lmfd&quot;]/span[@class=&quot;lmf&quot;]</value>
      <webElementGuid>870b4a22-de8c-43d8-90ca-b99b98496ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Login/iframe_Undo_ifinbox</value>
      <webElementGuid>e80d532d-d380-44d4-8a69-bafde6f1fc5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e_ZwLjZmZkZQLlAwV3ZQNjAGZ3BQx4Zt==']/button/div/span[2]</value>
      <webElementGuid>236399fd-87df-41f1-b192-28acf3a61e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/following::span[2]</value>
      <webElementGuid>ad9b933f-d9ce-4456-ac7f-e4c3f06db46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset your password'])[1]/preceding::span[1]</value>
      <webElementGuid>a50d6caf-a90e-4186-a820-e96e0eb1233e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NextSix']/parent::*</value>
      <webElementGuid>70d0f7f5-dc8b-4688-bc2c-90a4f7553788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>c39019fc-7235-4031-a495-04263e3a926f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NextSix' or . = 'NextSix')]</value>
      <webElementGuid>18e6e802-e60c-4a1f-a985-6f34c202300b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
