<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dashboard</name>
   <tag></tag>
   <elementGuidId>d3629fc4-d6bd-405b-8116-5bb367822d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.menu-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#kt_app_sidebar_menu']/div/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de971cff-2452-45f7-bc81-7d15a00d94f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-title</value>
      <webElementGuid>81ec3a2e-c808-4850-b6cd-19c91c895683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard </value>
      <webElementGuid>7f1e5ad0-71e9-42cc-af9d-44186851a162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#kt_app_sidebar_menu&quot;)/div[@class=&quot;menu-item&quot;]/a[@class=&quot;menu-link without-sub active&quot;]/span[@class=&quot;menu-title&quot;]</value>
      <webElementGuid>29a8210e-d524-4f28-a05d-907735e1dfa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='#kt_app_sidebar_menu']/div/a/span[2]</value>
      <webElementGuid>59870d9f-f9a7-45fc-a3f9-7ece693218c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update password'])[1]/following::span[8]</value>
      <webElementGuid>0eda86a1-bfbf-4820-b291-2b7048831d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::span[8]</value>
      <webElementGuid>30c7f255-ccfb-4c39-861e-1e99a00a0c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property'])[1]/preceding::span[2]</value>
      <webElementGuid>69a0420d-e5e4-4f26-a40e-904c108f95c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[1]/preceding::span[6]</value>
      <webElementGuid>565d4b24-cd9a-47ab-8346-2da3c1f13939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboard']/parent::*</value>
      <webElementGuid>e995d6e0-8c54-4126-91b6-c070c16e821f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>0e3e85f6-ec77-4ff9-b198-97afbfa8b8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dashboard ' or . = 'Dashboard ')]</value>
      <webElementGuid>d02c936a-61fd-46e8-b4b1-1627ea4aa38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
