<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Upload New Attachment_at-input-upload</name>
   <tag></tag>
   <elementGuidId>a5d2b9d9-d0c9-484b-a304-03863719aba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.at-input-upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/div/div/div[1]/div[2]/section/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7b290d7-6dd3-4fa3-8cca-4a4eb6ce981f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>at-input-upload</value>
      <webElementGuid>c07faf02-acc6-47d9-8717-e1b3fe9eac70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[@class=&quot;at-input&quot;]/section[1]/div[1]/div[@class=&quot;at-input-upload&quot;]</value>
      <webElementGuid>f9758a8c-2eab-4616-a673-960e78768d7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_create_app']/div/div/div/div[2]/section/div/div</value>
      <webElementGuid>8b87a87d-4e20-4eb2-8d90-e19789393854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>987a8f2f-20ac-4d20-83db-0c9920881a4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
