<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>17058a77-159e-4995-94f5-3a8a73e7d892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ua-img-list > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_modal_create_app']/div/div/div/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c64eef36-fec6-4ada-8748-3aebc1a7dbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://iprofstore.blob.core.windows.net/files/iroomz/unit/69cccf4b00c662fb81c17650/istockphoto-1131184921-612x612_tjeNNE5K.jpg</value>
      <webElementGuid>e6c9bffd-bb36-4c7b-9c9c-006a389a92f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[@class=&quot;at-input&quot;]/div[@class=&quot;ua-attachment-container&quot;]/div[@class=&quot;ua-img-wrapper&quot;]/div[@class=&quot;ua-img-list&quot;]/img[1]</value>
      <webElementGuid>0033cfc3-c587-4ad4-b399-a4fcded79dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_create_app']/div/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>236038cd-58a2-4a16-bb53-86537304383c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://iprofstore.blob.core.windows.net/files/iroomz/unit/69cccf4b00c662fb81c17650/istockphoto-1131184921-612x612_tjeNNE5K.jpg')]</value>
      <webElementGuid>ec5c3ec0-6a98-4775-a7f2-3d24a6b2a5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>8e17a0b5-4016-4a0c-bc6e-0ead6e7055e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://iprofstore.blob.core.windows.net/files/iroomz/unit/69cccf4b00c662fb81c17650/istockphoto-1131184921-612x612_tjeNNE5K.jpg']</value>
      <webElementGuid>59835f83-8e50-4055-a790-386b684128c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
