<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Managed By_managedByManagement</name>
   <tag></tag>
   <elementGuidId>9c26c63f-b6d5-4d62-936d-8fd90b13bbad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='managedByManagement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#managedByManagement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>105f18a4-4749-4b69-81b0-07bddd6ce017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>managedBy</value>
      <webElementGuid>3a78953e-75c4-42e9-9d3c-6caf51dd2168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a1427eb3-d099-4d9e-8884-991381d2c81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>managedByManagement</value>
      <webElementGuid>de46cd78-343d-4d5a-aaa9-1ef576a3ee58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>22a27ed0-02b7-4aee-a24d-9b278ed53e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Management Unit</value>
      <webElementGuid>85008917-67bd-4d8d-b0e6-b2fbb668287b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;managedByManagement&quot;)</value>
      <webElementGuid>c5660fd6-b962-455c-8e5e-f61e06b0656c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='managedByManagement']</value>
      <webElementGuid>60acdf3e-9f4c-4c26-85b1-1acde951a538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div[2]/div/div/div/input</value>
      <webElementGuid>beaa8fa0-e764-46db-a2ea-634dae1bf5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>f6f70eda-d632-4d20-8c30-5727f323796a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'managedBy' and @type = 'radio' and @id = 'managedByManagement']</value>
      <webElementGuid>3594c4d3-3d81-47a0-8106-94146f2a2e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
