<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postpaid_Prepaid</name>
   <tag></tag>
   <elementGuidId>fcb0806a-2aea-4528-b4e9-e89ff989966a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Prepaid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Prepaid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaf2e2bd-aea3-45f7-84b7-f5dc64b299c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roomData.0.smartMeterPaymentMode</value>
      <webElementGuid>2307a83f-0698-4d58-a650-d06bcd54ab02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9904c590-f84a-4ecb-af2b-3da35dea2e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Prepaid</value>
      <webElementGuid>78bef63d-9efb-4719-af89-f1bbeaca5189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>cf32b87e-cc11-4da8-b521-36ded0c4ded4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Prepaid</value>
      <webElementGuid>b9391210-9d46-4dc1-840b-d1cd4df2c98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Prepaid&quot;)</value>
      <webElementGuid>6a6cc1ae-1024-48d6-802d-7f43934bd5c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Prepaid']</value>
      <webElementGuid>e8ac5066-139a-4b10-82ed-8bcb28696669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[12]/div[5]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>5b9a5ba4-60d4-4e19-9715-ce740e943cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>115d183f-d308-47e3-a8a2-2ab0a4eb5941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'roomData.0.smartMeterPaymentMode' and @type = 'radio' and @id = 'Prepaid']</value>
      <webElementGuid>c1d0edc6-ed6e-4c85-9512-3e9439f68bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
