<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postpaid_Prepaid_1</name>
   <tag></tag>
   <elementGuidId>0eadfa3f-9eee-4b71-ab60-8850e5cc3a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Prepaid'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(13) > div.row > div.col > div.mb-3 > div.mb-3.d-flex.align-items-center > div.form-check.form-check-inline > #Prepaid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fabae5ab-837a-4df7-be90-cbfbc9632dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>roomData.1.smartMeterPaymentMode</value>
      <webElementGuid>ef733fe8-69cf-4394-9de6-821fbd45d0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2b9f4f2e-d71e-4327-bf1e-2f71e1ac5be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Prepaid</value>
      <webElementGuid>85a030bd-89ec-4edd-b4c6-e8d2babdf05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>94280eae-e1d8-4963-a491-f751e68ad033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Prepaid</value>
      <webElementGuid>b54bc83d-26f4-44ff-af20-3a914cc5601b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[13]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;mb-3 d-flex align-items-center&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/input[@id=&quot;Prepaid&quot;]</value>
      <webElementGuid>f5749342-b68e-404a-a7dc-72ac0e730ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Prepaid'])[2]</value>
      <webElementGuid>5cb661d0-5291-4a88-af13-15b06cd95e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[13]/div[5]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>7ce12214-9348-430f-ae98-fc7a97f01106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[5]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>fbc796f5-72a3-4b29-aae1-af00244e4319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'roomData.1.smartMeterPaymentMode' and @type = 'radio' and @id = 'Prepaid']</value>
      <webElementGuid>9c76442b-2f87-4411-90d8-15ce0ffac2ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
