<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Management Unit_managedByNonManagement</name>
   <tag></tag>
   <elementGuidId>74434664-d7aa-4c97-890d-e50848646245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='managedByNonManagement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#managedByNonManagement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8827417f-fcac-49dc-a9c8-a85b27993b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>managedBy</value>
      <webElementGuid>5a2051ca-e369-4815-b242-2a824dd59c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c5e5a0b9-0a12-4ad9-af10-22bd46d174c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>managedByNonManagement</value>
      <webElementGuid>1710bc34-7a2e-442c-ba83-73067c907a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>72888e15-6f71-4c11-9892-d25ac3530f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Non-Management Unit</value>
      <webElementGuid>bdc50f8e-15c3-4da8-b706-05dd260ad8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;managedByNonManagement&quot;)</value>
      <webElementGuid>47c07951-5ada-4673-95de-063179756849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='managedByNonManagement']</value>
      <webElementGuid>70232533-1243-4d07-970c-4e361fd885d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>e066a99d-e371-47d7-a4db-22763e5e12ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>11a2e78d-3413-435f-abc3-242ec501472f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'managedBy' and @type = 'radio' and @id = 'managedByNonManagement']</value>
      <webElementGuid>f62e0f95-12a8-4f6e-a164-38a991750b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
