<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Management Fee_managementFee</name>
   <tag></tag>
   <elementGuidId>d281ef39-97e5-4daf-8ab5-571859296259</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='managementFee']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;managementFee&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9033c38f-6362-4dc8-9dad-470035b9ecd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>managementFee</value>
      <webElementGuid>c774d2bd-7bc0-4668-929f-b30cd2747893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control no-border</value>
      <webElementGuid>0996b4c7-1c24-48b8-a9e5-016c4ae2fc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68462545-5c8c-4a69-b1a1-0f6263122856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Management Fee</value>
      <webElementGuid>a6e4e891-19dd-4ca0-96ec-a7ed6c2bada6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>336a1bda-d7e2-4a09-a9d7-8c8f7b16dee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control no-border&quot;]</value>
      <webElementGuid>07085806-c39b-474d-8ab1-bee539ad20ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='managementFee']</value>
      <webElementGuid>dd817ae8-e71f-4be4-9142-688fe95fccb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[3]/div/div/div/input</value>
      <webElementGuid>32677b1c-89b0-4014-8723-b57f15c7313e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>2a67b52f-e2af-4546-b79a-b76fc16aabe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'managementFee' and @type = 'text' and @placeholder = 'Management Fee']</value>
      <webElementGuid>4e4ea815-956a-4976-a538-9f7b0b49ba19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
