<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit Name_propertyUnitName</name>
   <tag></tag>
   <elementGuidId>d1fdc0f6-b9d3-4eef-93fa-e284209b4a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propertyUnitName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='propertyUnitName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f028b035-810e-46ec-89bd-445ccea53488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Unit Name</value>
      <webElementGuid>4a3bfe55-3457-4fd0-a088-f71a521676fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a60f004-6cee-4dd7-83f6-81f8aeef35f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propertyUnitName</value>
      <webElementGuid>3036a9bc-9bb6-4cbc-ad92-caf037d67643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>898c9cff-49f5-46d6-94c4-e735df2cf86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propertyUnitName&quot;)</value>
      <webElementGuid>988ce24c-8360-4d7f-b9f6-e310bf990e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SEZ3465</value>
      <webElementGuid>8cc03d88-8be7-41ee-a0a5-76382d4b2f11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='propertyUnitName']</value>
      <webElementGuid>62453a2e-dedb-48a8-b2ee-19be5f5c1cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div/div/input</value>
      <webElementGuid>3dcb8a94-7b6f-4413-9b3f-d2ea51969410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>4bf0a83a-ce47-4e78-80a3-606c3183b2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Unit Name' and @type = 'text' and @id = 'propertyUnitName']</value>
      <webElementGuid>bf990515-9839-40fb-99aa-86d66c9d8275</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
