<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Update</name>
   <tag></tag>
   <elementGuidId>9fe9e27d-d8e4-4f93-81e9-70f54252d814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Update' or . = 'Update')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.indicator-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_modal_create_app_form']/div[9]/button[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d5f47af-dc6a-40eb-a6c3-42f70f0a4af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>indicator-label</value>
      <webElementGuid>462c5845-e8bd-49c5-93d9-f5e3309dc1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>cb169fcc-84f6-4a9a-b607-0b8c07922f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;d-flex pt-10 modal-action&quot;]/button[@class=&quot;btn btn-lg btn-primary&quot;]/span[@class=&quot;indicator-label&quot;]</value>
      <webElementGuid>59da4bc2-9a4a-490f-a3a7-860d71d91757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[9]/button[2]/span</value>
      <webElementGuid>a967381e-edd1-487d-b824-4904e6bd0f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::span[1]</value>
      <webElementGuid>73ee013e-9f66-440a-a993-7457bb873f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::span[1]</value>
      <webElementGuid>7a964559-affb-46ea-be52-547f4b0c6bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update']/parent::*</value>
      <webElementGuid>761eed8e-15ff-47ec-a745-8c7917ffe75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>6370fb3c-022c-415c-bf92-0ddc38c5a18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>b74c04d7-0dbe-43df-82fe-b2ea5aa3728b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
