<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Type to search room_css-liki3c</name>
   <tag></tag>
   <elementGuidId>af91d466-b730-43cf-a0f2-1e5642328ba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-liki3c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_modal_create_app_form']/div/div/div/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>035c0226-f21d-4675-b00e-a592e619002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-liki3c</value>
      <webElementGuid>aaa8abbc-71c1-4067-842e-52bc98e5395b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;current&quot;]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-12&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;css-b62m3t-container&quot;]/div[@class=&quot;css-r5vfb9-control&quot;]/div[@class=&quot;css-t6uyiw&quot;]/div[@class=&quot;css-liki3c&quot;]</value>
      <webElementGuid>4ad7557d-0894-41b7-a2c3-7bfb93c359ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>de2126bc-dc6b-4630-8c3b-60ddcc9e9c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type to search room'])[1]/following::div[1]</value>
      <webElementGuid>f21b6bad-78f2-4dca-8b15-07ec3ffbad7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Name | Room Name'])[1]/following::div[5]</value>
      <webElementGuid>3b64c18f-dfd9-4c4f-8353-b8bf3b627608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Rental Fee'])[1]/preceding::div[2]</value>
      <webElementGuid>7fec29aa-8529-434a-9e02-f72d18b2ac95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>c81a7c84-6c96-4268-86b2-5614ebc16bad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
