<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Advance Rental forMonth (RM)_advanceRental</name>
   <tag></tag>
   <elementGuidId>4bf7524c-9b90-47c0-8d13-89deb93c8777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='advanceRental'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.col-sm-12 > #advanceRental</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d60995d-573e-462a-8a47-03e1f9e5efe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Advanced Rental for 2 Month (RM)</value>
      <webElementGuid>17f809c9-fe49-49a4-9453-635007bb46b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>advanceRental</value>
      <webElementGuid>b5afa7cd-c96d-477b-91ea-5b40e00d3fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b47b159-ceb9-453f-9017-436280eac220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advanceRental</value>
      <webElementGuid>91ed11b4-6468-4efd-b614-7054588dc7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>3d1c9024-6f1a-424e-a608-9716e1b892dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>8,600</value>
      <webElementGuid>a79ddde7-f1bf-4b82-9e11-60ccb5bbaac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;current&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;rental-detail row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;mb-3 align-items-center row&quot;]/div[@class=&quot;col-md-6 col-sm-12&quot;]/input[@id=&quot;advanceRental&quot;]</value>
      <webElementGuid>3fe82064-9181-4a56-8ad8-565333b101fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='advanceRental'])[2]</value>
      <webElementGuid>45b5eb18-e675-4f16-a507-e628fe502ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div[4]/div/div/div/input</value>
      <webElementGuid>694f8d48-62e0-4905-ad88-4afeed0ecee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>1f21bda4-5a5d-4e35-8da7-21a62e84a5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Advanced Rental for 2 Month (RM)' and @name = 'advanceRental' and @type = 'text' and @id = 'advanceRental']</value>
      <webElementGuid>3da30b88-d055-465c-8473-09d8ff7db7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
