<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Number of Tenant_numberOfTenant</name>
   <tag></tag>
   <elementGuidId>bf9f1f63-6148-48c3-b4d2-16c04a5a4d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfTenant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfTenant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65abeae8-3384-4675-820e-6c7fa93f3873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Number of Tenant</value>
      <webElementGuid>6d445e9b-d8e8-43e2-b942-1806f32426dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3faafd5a-e6c1-43f7-8dff-edafa60239ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfTenant</value>
      <webElementGuid>47191bea-f337-4d94-a03e-3d3ff7e2f4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>240ee510-7d35-4d77-92f6-d86b0f268309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfTenant&quot;)</value>
      <webElementGuid>fd48a23d-5496-4456-8e41-df924f332c72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfTenant']</value>
      <webElementGuid>795a06a7-e0d7-4378-beae-517b3ec61341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>29b9e4e3-e93b-4b99-ae63-e89696bee50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>9879f1dd-1c27-4333-afa3-dac4aee8ed54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Number of Tenant' and @type = 'number' and @id = 'numberOfTenant']</value>
      <webElementGuid>2329faa3-4391-4373-a4f6-c92014d1ee06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
