<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Access Card Deposit (RM)_accessCardDeposit</name>
   <tag></tag>
   <elementGuidId>6da0962d-318a-4a66-80d4-7113020ad9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accessCardDeposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accessCardDeposit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>123490d9-9bd3-4f9e-805f-31750d80f037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Access Card Deposit (RM)</value>
      <webElementGuid>6fcd811b-0b63-47e8-84cf-9d94e98a2f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7d1be92-1a62-45c7-9263-2083c55c49b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accessCardDeposit</value>
      <webElementGuid>d266ccba-f2e2-4cf9-98b4-db6c6c0bc92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>0f73e772-dd6b-4f60-872c-b24efd2f7f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accessCardDeposit&quot;)</value>
      <webElementGuid>e6609975-c342-429a-8361-b4f87320456d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accessCardDeposit']</value>
      <webElementGuid>5c7eed1c-f064-43f9-a9fc-4a79b0f1e4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div[4]/div/div[4]/div/input</value>
      <webElementGuid>4952953d-1c9e-4964-9695-79860694966f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>573a0460-446f-4740-80ec-7aaaca717603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Access Card Deposit (RM)' and @type = 'text' and @id = 'accessCardDeposit']</value>
      <webElementGuid>1b0c72df-24a2-447a-82d2-8e4e693d406b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
