<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Security DepositMonth (RM)_securityDeposit</name>
   <tag></tag>
   <elementGuidId>f39b0b37-eddb-4c92-9328-b953b026cf1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6 > #securityDeposit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='securityDeposit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b330726e-98ea-4391-8641-171f4bf4b13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Security Deposit 1 Month (RM)</value>
      <webElementGuid>069e2fdd-c48d-416d-9752-39b003b96137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>securityDeposit</value>
      <webElementGuid>e829ce04-2954-4491-99b2-c668f649ed4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6816fd3a-861f-406b-89ad-a19d3a76aab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityDeposit</value>
      <webElementGuid>8853a161-8bab-456e-9ffd-d32bc2314f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>ccaecf4b-db6d-466a-8958-92dacbc18050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;current&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;rental-detail row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;mb-3 align-items-center row&quot;]/div[@class=&quot;col-md-6&quot;]/input[@id=&quot;securityDeposit&quot;]</value>
      <webElementGuid>663a4cdc-351b-4f32-bda7-002c5a254ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='securityDeposit'])[2]</value>
      <webElementGuid>2f55d5cf-45fe-4f87-bd56-55e0a081eb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div[4]/div/div[2]/div/input</value>
      <webElementGuid>de4d04e9-c059-4968-aff9-523621c26580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/input</value>
      <webElementGuid>3c376a66-ef42-41ef-8303-b51934b90f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Security Deposit 1 Month (RM)' and @name = 'securityDeposit' and @type = 'text' and @id = 'securityDeposit']</value>
      <webElementGuid>b21c7ffa-2af4-46a9-a410-cfce8c521ac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
