<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select oneMalayChineseIndianOther</name>
   <tag></tag>
   <elementGuidId>b51acac8-64ad-410c-97bb-0daf6d250738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenantRace1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tenantRace1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a0e1b25-6271-48e7-a34d-84fbe22afcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Race</value>
      <webElementGuid>838b20cd-ba28-40ec-84c9-37f88d861e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenantRace1</value>
      <webElementGuid>ad90c537-c6cf-4c7d-a825-6cb7e2e83bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-sm</value>
      <webElementGuid>107feeb2-3923-443d-8100-a9932aaa548f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenantRace1</value>
      <webElementGuid>9b73b672-cf97-41fc-be76-8c295ece8a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select oneMalayChineseIndianOther</value>
      <webElementGuid>8357ae34-30ac-4fc2-a8c3-c6449d108f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenantRace1&quot;)</value>
      <webElementGuid>65c759df-c6ad-4ba3-9866-f9ae2632372b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tenantRace1']</value>
      <webElementGuid>a00d0ae4-47d1-4c31-9413-9788b3bd0e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div[2]/div/div[7]/div/select</value>
      <webElementGuid>4a4d27db-aa6b-450e-9329-4a67406dafa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant 2 Details (if any)'])[1]/preceding::select[1]</value>
      <webElementGuid>8ca9e15f-1c8f-4cc4-82b2-7cfa9f880af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name :'])[2]/preceding::select[1]</value>
      <webElementGuid>28dfaab0-afdc-4159-8d7b-3ca5ea2644b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[7]/div/select</value>
      <webElementGuid>ff8ae656-615f-4a74-98f1-969d7d040180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Race' and @name = 'tenantRace1' and @id = 'tenantRace1' and (text() = 'Select oneMalayChineseIndianOther' or . = 'Select oneMalayChineseIndianOther')]</value>
      <webElementGuid>eaddbde0-d855-4a89-9358-235c833f2f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
