<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select oneMrMrsMs</name>
   <tag></tag>
   <elementGuidId>aaa99ea1-da86-4006-95e3-bc594c245abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenantTitle1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tenantTitle1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>50203fb2-4b43-4a1f-bde4-81c6e744c8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>7f0dd956-e534-47c0-8127-3047531d2ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenantTitle1</value>
      <webElementGuid>46f0ab2d-10e6-4be4-91b1-06e3385d73d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-sm</value>
      <webElementGuid>6c69ed9a-e8d9-4087-9bb2-33ec967034ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenantTitle1</value>
      <webElementGuid>406b1fb2-d38d-408b-9b03-78b60a38f733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select oneMrMrsMs</value>
      <webElementGuid>743e9cba-299d-49bd-8480-66a3bd872353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenantTitle1&quot;)</value>
      <webElementGuid>0e42e1ee-ac4c-4d00-a2b5-91cc6830b9aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tenantTitle1']</value>
      <webElementGuid>da90600d-1870-45fe-8a9c-0b9d8b5db4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div[2]/div/div[2]/div/select</value>
      <webElementGuid>977a5a59-c187-4f7e-9a43-16ee0995c57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRIC'])[1]/preceding::select[1]</value>
      <webElementGuid>ad7567e3-8444-46f7-8456-34d9f776a9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/select</value>
      <webElementGuid>cc673eec-1e6f-4a15-bb4c-4724c0350d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Title' and @name = 'tenantTitle1' and @id = 'tenantTitle1' and (text() = 'Select oneMrMrsMs' or . = 'Select oneMrMrsMs')]</value>
      <webElementGuid>25599222-9a7c-4632-8023-989c83cadbb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
