<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select one6 Months1 Year2 YearOther</name>
   <tag></tag>
   <elementGuidId>bbb18c0a-06a6-491e-a9cf-90c20bb32c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenancyPeriod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tenancyPeriod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>743a5c5b-d63c-451b-94b3-7cff70bf5fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tenancy period</value>
      <webElementGuid>1c8b1b8c-38b0-4a97-81f1-8f08cdc4f998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tenancyPeriod</value>
      <webElementGuid>0df4e8db-56ad-4352-9166-6599bda6192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-sm</value>
      <webElementGuid>924aa820-0864-4956-b656-9a47b613f19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenancyPeriod</value>
      <webElementGuid>79550cc5-9a16-4249-8b59-64fa86273d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select one6 Months1 Year2 YearOther</value>
      <webElementGuid>6442cd09-490b-483c-b022-f9ea2cf686b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenancyPeriod&quot;)</value>
      <webElementGuid>26890f95-4089-4078-a324-404f34ed839a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tenancyPeriod']</value>
      <webElementGuid>8660b597-c933-4aec-9ade-aebb8892a546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div/div[2]/div/div/select</value>
      <webElementGuid>3504bf8a-9fbd-4775-8914-5c7f30eaeb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenancy Period'])[2]/following::select[1]</value>
      <webElementGuid>92203df0-ea61-4b30-9ecf-f63dab91892a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimate Check In Date'])[1]/preceding::select[1]</value>
      <webElementGuid>339d104e-83c4-4011-9911-7441a8a1fde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div/select</value>
      <webElementGuid>102134bb-93cb-4515-ac59-7f6fb1b0090e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@placeholder = 'Tenancy period' and @name = 'tenancyPeriod' and @id = 'tenancyPeriod' and (text() = 'Select one6 Months1 Year2 YearOther' or . = 'Select one6 Months1 Year2 YearOther')]</value>
      <webElementGuid>7d9285cd-baad-42ce-ad99-a7d92200d493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
