<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KARAN PLUS</name>
   <tag></tag>
   <elementGuidId>55943d5d-0db5-4233-9116-ab72f2351e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.fullName > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97e985c2-7e71-4b8b-9fa6-3c58ec437fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KARAN PLUS</value>
      <webElementGuid>dbf5458b-53cc-49ae-a220-9e4c42549c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_datatable_vertical_scroll&quot;)/tbody[1]/tr[@class=&quot;mainRow&quot;]/td[@class=&quot;fullName&quot;]/span[1]</value>
      <webElementGuid>e2776d7a-9dbd-42d2-89a3-3d767c758b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[4]/span</value>
      <webElementGuid>11eafaa9-455f-470a-b6b3-9dedf4ab3492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KARAN PLUS'])[1]/following::span[2]</value>
      <webElementGuid>edcb8473-7174-4378-9f19-3768cf273e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Due Date'])[1]/following::span[3]</value>
      <webElementGuid>b52d5758-90b7-4d7d-bc71-b6def9e93047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sharkdisgraced@yopmail.com'])[1]/preceding::span[3]</value>
      <webElementGuid>7ae4d33a-cb2c-44f0-bdb9-ff4a82d1ba8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::span[4]</value>
      <webElementGuid>d2428243-caed-4de2-a0db-15e6cbb7806f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>3f9fa92f-4359-4b5a-aedd-398c56a72a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KARAN PLUS' or . = 'KARAN PLUS')]</value>
      <webElementGuid>2cc8bdc8-3320-40f1-b4cb-339cd20c4877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
