<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KELLY</name>
   <tag></tag>
   <elementGuidId>59eb76fe-5e47-4e59-8a6e-f7bdc341fb1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.tenant > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62b2bec7-2bdc-4efa-aeee-b08054909fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KELLY</value>
      <webElementGuid>b42d859a-38cb-4473-8916-a1d3043d697d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_datatable_vertical_scroll&quot;)/tbody[1]/tr[@class=&quot;mainRow&quot;]/td[@class=&quot;tenant&quot;]/span[1]</value>
      <webElementGuid>0a155c1c-0d90-44e1-aaf2-730a429aea52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[3]/span</value>
      <webElementGuid>3ea6b1bf-0b80-47c9-9a3b-e51f04b067d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMK 8'])[1]/following::span[2]</value>
      <webElementGuid>022967c8-b8e7-4ba4-b2cb-2e11b851e854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::span[3]</value>
      <webElementGuid>ecbac112-2c69-4ed7-81dc-0f80342fff7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='canyouseethat321@yopmail.com0173510996'])[1]/preceding::span[1]</value>
      <webElementGuid>42371d25-565d-44c7-ba32-cd3ca93321bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/preceding::span[3]</value>
      <webElementGuid>104a783b-1308-4c3e-9b20-a0ca40fd5f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KELLY']/parent::*</value>
      <webElementGuid>d66cfee1-6339-45d5-853c-72adb6bde14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>986b9285-37cd-46a6-806b-db01e0a78f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KELLY' or . = 'KELLY')]</value>
      <webElementGuid>994f94f8-d774-4908-92c6-4505998f3bf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
