<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Affin Bank Berhad</name>
   <tag></tag>
   <elementGuidId>5d06911e-35f1-4d0c-871d-322f0b2c0524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-7-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9c7ba70-2554-419c-9740-693cb08b71f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-x0pmqf-option</value>
      <webElementGuid>b2e4191e-4e21-4304-a0a4-bf2b2948e852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e02a51d-4219-40dc-b20b-bfec1b3b9e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-7-option-1</value>
      <webElementGuid>62d62d38-3b68-4167-a970-2d51ceb9a783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>77f3adac-ce94-4b2e-927f-2d8fd8ee3145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>edc46201-27e9-4885-9f1c-299de2562333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>712b1e66-25cc-4b26-bf0b-dabfef0778e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Affin Bank Berhad</value>
      <webElementGuid>27b91172-ddd7-4a9a-895d-a3c9d64f32f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-7-option-1&quot;)</value>
      <webElementGuid>e094b689-eb3b-447d-a9fc-02a8e32a3411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-option-1']</value>
      <webElementGuid>34b1064c-00e9-40f8-807b-6002b16d4735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-7-listbox']/div[2]</value>
      <webElementGuid>8da85727-a4d8-42e5-adac-edb05754ea96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Bank'])[2]/following::div[1]</value>
      <webElementGuid>c0c50b82-4572-4080-af6d-5173684eb59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Bank'])[1]/following::div[8]</value>
      <webElementGuid>8c53e361-22fe-458c-8783-61da59e4c4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agrobank'])[1]/preceding::div[1]</value>
      <webElementGuid>b7ee8bb5-ac93-4314-abc0-92fde3e21673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alliance Bank Malaysia Berhad'])[1]/preceding::div[2]</value>
      <webElementGuid>a4655872-f7cf-4a44-9318-57bbc43edd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>03d02bff-1c98-4bc7-b767-20abcb703185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-7-option-1' and (text() = 'Affin Bank Berhad' or . = 'Affin Bank Berhad')]</value>
      <webElementGuid>8539a808-ef6a-46d0-913c-0ae5c22c730f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
