<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TIN_tin</name>
   <tag></tag>
   <elementGuidId>ea0d2e7f-3948-4801-8496-bb0d674d7e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dfbe4e2-7142-4e0e-9821-4807b5614cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tin</value>
      <webElementGuid>10f00aa9-f28b-448e-806b-df693f065d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>517cc96c-783a-4c4a-a565-e00d176f7efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tin</value>
      <webElementGuid>cddb3b2e-d93b-4900-84d5-910af4c9c156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a76ea41f-5f3d-4605-bcb5-6d1bd1492436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>5f4b357c-0fc6-43d2-a186-8d3b2a4e2d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 col-sm-12&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;mb-3 d-flex align-items-center&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/input[@id=&quot;tin&quot;]</value>
      <webElementGuid>961a0c04-c9b2-4506-8a73-d39c101cbec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tin']</value>
      <webElementGuid>157b9556-8c8f-4192-bff7-c4073da70cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[4]/div/div/div/div/input</value>
      <webElementGuid>651d848a-fdc5-448b-8603-741303ee3b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>cf22af56-07bb-4524-8e33-f4f83bcffc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tin' and @type = 'radio' and @id = 'tin']</value>
      <webElementGuid>c0e760ca-b39b-4c8e-96f9-eaf573ef4a71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
