<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Line 1_line1</name>
   <tag></tag>
   <elementGuidId>f65e5d4a-e2fb-444d-a754-30971b807e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#line1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='line1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a254e839-e422-4ff6-99bf-63ff9824c424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>3e03cc87-841f-4ba0-ab19-ca700c0f49ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fd81ddc-00d7-408b-bdce-d518f0ca96e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>line1</value>
      <webElementGuid>67c646be-1c4c-44b1-bd52-11c297132cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5c45c397-f6ad-4b2f-be32-e613795368d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;line1&quot;)</value>
      <webElementGuid>77f0a25a-0e2f-441e-901f-81bdb7ecc030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='line1']</value>
      <webElementGuid>b577de84-597f-43a3-a2cc-20354defce38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[5]/div/div/div/div/input</value>
      <webElementGuid>0fa1c5f4-c486-4f69-b241-3a6ce38f3442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>86ba381b-7e56-42c6-8e6c-ad40e8fcff0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Address Line 1' and @type = 'text' and @id = 'line1']</value>
      <webElementGuid>8041416c-5e44-45e0-99b5-1f4d62b71d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
