<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Name_accountName</name>
   <tag></tag>
   <elementGuidId>11184c20-f839-423c-a218-6ab5d9c38757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0e8bd1e-954b-4e01-b50b-698ff5d39fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Name</value>
      <webElementGuid>f428a64a-5464-44e9-b01c-c731517ff48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ae5eaa0-b1af-4e4f-af8b-364163d5bbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountName</value>
      <webElementGuid>d0362ebb-82f5-4b99-bc71-a36992c6a061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3988568b-913a-4d9d-ac86-09b5804330ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountName&quot;)</value>
      <webElementGuid>bb82bd25-0e1b-496f-aaae-15efa0aefe82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountName']</value>
      <webElementGuid>972f1c30-a1a3-4d7b-8646-773106e13d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[4]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>bd8efea4-4dce-416d-9c2f-e94493b8b2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>54a7f4f5-2c3f-43d9-9880-02eb0d99ecb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Account Name' and @type = 'text' and @id = 'accountName']</value>
      <webElementGuid>f760c2ed-cbed-468f-a1f3-7b804d215cc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
