<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account No_accountNo</name>
   <tag></tag>
   <elementGuidId>3b7d4717-25b3-4b4b-97d8-dfef26a1d3f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89f72b27-5c16-43a3-bca2-a6f291c3c29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account No</value>
      <webElementGuid>08354c50-d3d3-4e0d-93c2-8a043638c1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bed3141d-dd53-493a-b13b-25fa2f942c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>d40616df-31cb-46a0-985f-46cd8e28840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>519b9124-521a-44e8-8b17-03c5b0ed47d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountNo&quot;)</value>
      <webElementGuid>24ca8917-bb1d-47aa-9449-6050bf8b5fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountNo']</value>
      <webElementGuid>a6719b0e-57db-4a7c-bbdd-4c80b7c684bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[4]/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>b94121ad-7437-4932-aba4-7e9aac66156a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>7d56adeb-039a-47cb-a2e0-96413bf31b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Account No' and @type = 'text' and @id = 'accountNo']</value>
      <webElementGuid>12ade8e6-e7d4-440c-8578-0ad5b261e16f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
