<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Name_accountName</name>
   <tag></tag>
   <elementGuidId>4d80a522-b670-421f-bc2b-e1d7f1b4984e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65391d58-9a6d-4dba-9986-4c6bb1f17734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account Name</value>
      <webElementGuid>d2bf40e9-eedb-405f-a8a1-4226a91eb0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d419a266-3406-4638-9730-e7732060faeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountName</value>
      <webElementGuid>0fbef01a-ae37-46ee-a4eb-fff1979d0f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>931fde9f-2b2c-4d3b-8031-130bc4f36c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountName&quot;)</value>
      <webElementGuid>64ae74ca-b86e-4829-83b5-04874475c439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountName']</value>
      <webElementGuid>74d1fbbd-aaa8-4901-a9f1-98ab5a9ab19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[4]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>276c04d6-9eec-4781-8527-65114917d8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>c412f285-75ad-49c9-ad4e-2515dcb8abfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Account Name' and @type = 'text' and @id = 'accountName']</value>
      <webElementGuid>496f32a5-62b7-4871-8776-46f04b6e9e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
