<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account No_accountNo</name>
   <tag></tag>
   <elementGuidId>388fc600-e7b0-4ffa-86da-885e08e4b5f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a616da2-614f-46a4-8e56-fce01d593455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Account No</value>
      <webElementGuid>3bcfb638-b76e-4b71-83d4-08d479640605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f16ba808-085d-42b8-b1b7-b29bcf2c4222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountNo</value>
      <webElementGuid>cc8172ee-7868-4616-bb33-42ad5a99e4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a002b505-59fd-476e-8ade-b0449f172060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountNo&quot;)</value>
      <webElementGuid>5fada3ca-892d-48b6-8b77-bbc109118a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountNo']</value>
      <webElementGuid>42012639-bad5-417d-87ec-b8dbd33da3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[4]/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>89467d82-11af-46be-b8c6-2335fe46b8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>37e8cf5e-7c7d-47d9-bb42-ae1831694040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Account No' and @type = 'text' and @id = 'accountNo']</value>
      <webElementGuid>6b2fbce5-3462-4cd9-9267-d72db0256187</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
