<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Area_area</name>
   <tag></tag>
   <elementGuidId>d8f1c2d7-1061-4abb-a2a0-3779077b0a8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a21efa3-8f29-4ec3-bf99-e3be1af10a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>cb5e97e0-e1a0-4384-88e3-dc50b41fe653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be4217dd-cf08-4c9e-b1bd-438c31279b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>area</value>
      <webElementGuid>14eeec4b-ba8c-434e-b327-e381a7ba6a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7b99b2a5-ccfe-4cc8-875d-a78eb19e66bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;area&quot;)</value>
      <webElementGuid>747d0cc9-ea12-4714-9ec6-306c42ca2c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='area']</value>
      <webElementGuid>028bf613-6951-4c31-84f9-436396106e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[5]/div/div[3]/div/div/input</value>
      <webElementGuid>2fae5bc6-562e-464e-a327-27e0562b035f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]/div/div/input</value>
      <webElementGuid>7620b2c5-3494-438b-bb2f-a3de761c750c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Area' and @type = 'text' and @id = 'area']</value>
      <webElementGuid>9e476f00-6bd1-46dc-915c-2a33decbfc50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
