<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Line 1_line1</name>
   <tag></tag>
   <elementGuidId>cc59e354-481b-414a-80a8-73d8a9735e86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#line1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='line1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb7422c8-5b16-4d94-912a-48113e0f47fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>6f94abdd-6fae-466f-842c-9a7bd178e41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94d9a2b7-df8d-4b49-9308-e5a3b1f3c1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>line1</value>
      <webElementGuid>f23cc388-08bd-48dc-a962-2bab6aa75e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f30db34-471a-4836-ad28-3c326724d02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;line1&quot;)</value>
      <webElementGuid>38733dd4-4e79-4734-a5b2-f8ebcfa73558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='line1']</value>
      <webElementGuid>eeece769-7f5b-4773-a50a-c860c88e9bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[5]/div/div/div/div/input</value>
      <webElementGuid>9cc21253-d411-4f5d-8f2c-c526c78d5b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>b6138036-b46e-4070-a263-9da3b2b97681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Address Line 1' and @type = 'text' and @id = 'line1']</value>
      <webElementGuid>7202e781-f7e4-4d5a-867a-7b4c1d4ee4d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
