<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_State</name>
   <tag></tag>
   <elementGuidId>e40ced7d-4834-4e63-92df-6b1d623205a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-b62m3t-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[7]/div[3]/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>423f6ede-278b-4df4-b900-b33def287ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-b62m3t-container</value>
      <webElementGuid>77d35edc-60f5-4e18-98be-9b9cfbcc1da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State</value>
      <webElementGuid>4c7b70c2-413f-465d-b9b8-b2708846f1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[7]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-sm-12&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;css-b62m3t-container&quot;]</value>
      <webElementGuid>ccc0b8c3-4bfa-4a62-b468-274135bbf761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[7]/div[3]/div[2]/div/div</value>
      <webElementGuid>7b2f383c-a476-46da-86f3-6731a15d236f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::div[1]</value>
      <webElementGuid>4b6d3a12-4ec0-4501-90ca-29daef0669cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div[2]/div/div</value>
      <webElementGuid>1fbe034a-afb8-4810-845a-8d9db896f466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'State' or . = 'State')]</value>
      <webElementGuid>7675c03a-796a-4f16-98f8-023d56a4cbcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
