<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nickname_nickname</name>
   <tag></tag>
   <elementGuidId>cf993d3f-1d6f-409c-ae2b-7e63ffa8b3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nickname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nickname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10b6a6c8-fa5c-4cd4-a634-14011620a925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nickname</value>
      <webElementGuid>67e56387-44aa-4dbe-b71b-6e7d26a2b774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0daacb4a-359d-44d4-8898-b8e86a799ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nickname</value>
      <webElementGuid>2b9d5911-c267-4bd5-b643-5924012ccb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae3278e2-4538-47e5-903e-09a44b6983b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nickname&quot;)</value>
      <webElementGuid>5b6a994e-b3f9-4727-803e-b012dc32143d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nickname']</value>
      <webElementGuid>4bd5458a-6d70-416e-bd61-d4b0b8131e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>b1a79bbc-1287-4c16-b487-45e66ad190a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>99d1c8d5-37be-46b7-94fe-9b9aef952f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nickname' and @type = 'text' and @id = 'nickname']</value>
      <webElementGuid>b90e77e2-80f9-4222-9fee-32be42c44f73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
