<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Relationship with tenant_relationship</name>
   <tag></tag>
   <elementGuidId>cec15631-3bf0-4436-8175-867fb442fd95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#relationship</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='relationship']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4b82828-f5c2-4336-872c-0163aff64352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Relationship with tenant</value>
      <webElementGuid>cb85880f-6c1c-49ee-ba89-d12aafb36463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7060d7da-df42-44a6-855f-d58836686356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>relationship</value>
      <webElementGuid>18a849e7-dd51-4a59-bff9-657ce9bab094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>58f4c9e0-e9d2-4838-82cb-15de7476987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationship&quot;)</value>
      <webElementGuid>32238f42-e7fc-4440-8684-fa8bfe46f875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='relationship']</value>
      <webElementGuid>95df2f28-63dc-4f0a-bcda-0d256144c312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[5]/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>d1ac0f31-a581-4873-874b-b25b1d195406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>98174ca9-f0da-4044-84a9-ba80f48f75fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Relationship with tenant' and @type = 'text' and @id = 'relationship']</value>
      <webElementGuid>46b6a39b-532b-4116-aff2-bfca5a02cd76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
