<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact No_emergPhone</name>
   <tag></tag>
   <elementGuidId>78eb4d1b-c7a4-4ee0-9c94-5deadd3fc6fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emergPhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emergPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ced143e7-7507-4d6a-b68d-4005dd1ba761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contact No.</value>
      <webElementGuid>3321c864-07f7-4288-ba53-b7ae1686b16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1296fdf0-7603-4862-8cbb-dd91eaf017d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emergPhone</value>
      <webElementGuid>d6f0c464-4308-44fe-8a6d-67c8638eb90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1683a9ec-e5a7-4a93-bf6f-3fae3709af4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emergPhone&quot;)</value>
      <webElementGuid>6bde2895-7841-47ea-a0c9-9b5dc8244735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emergPhone']</value>
      <webElementGuid>5d618243-3f99-416b-bfa8-dd19c757d16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[5]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>eeb0fd6d-0095-4d68-a3a2-fc9ffe744a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>48ecf063-422d-4194-abc7-6eb1f2cc4a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contact No.' and @type = 'text' and @id = 'emergPhone']</value>
      <webElementGuid>052944a3-a0b8-4296-86a1-eedac3ab1b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
