<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tenant Sign Up Url_url</name>
   <tag></tag>
   <elementGuidId>706afbf4-f3a4-4445-b566-77e47ddddfc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='url']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50c5fe55-c37d-4ff5-96d3-dbbe1e9234c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Sign Up Link</value>
      <webElementGuid>8b5488ce-d857-41c2-ab7b-85571fcd3a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3ec068d-55d1-40d6-8045-1b246619c8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>url</value>
      <webElementGuid>6449f2b7-dab8-4883-a196-29214233985e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>534522e2-0875-4a3f-bbc2-70559578d76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://sit-tenant.iroomz.com/signuplink/DAGvpcOc3RpVE9eoV0KK77fp6WML9sRKSxrWJaGS38AqvKy9ufrxTbzIogDyisaj</value>
      <webElementGuid>9cee1a11-d8f2-479a-bb30-ccf6d1592654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;url&quot;)</value>
      <webElementGuid>092ebc05-2a17-4282-952c-c7c6f5242c2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='url']</value>
      <webElementGuid>b4434dfd-1998-4b54-b660-e091db131141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div/input</value>
      <webElementGuid>39236181-cca1-4a92-aee1-153ddb0bd1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>a0d4e31a-295e-404a-9da4-550eede4bc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Sign Up Link' and @type = 'text' and @id = 'url']</value>
      <webElementGuid>e4aac459-e9cc-4944-acf5-d2045665c6e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
