<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_emergName</name>
   <tag></tag>
   <elementGuidId>5b90ea53-1a9e-4457-835e-dd640538d2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emergName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emergName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fb8eebf-a97a-4530-a810-a08ab1a5f9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full Name</value>
      <webElementGuid>e001757f-6088-463d-8fd2-b870ca5dda21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0783947-c7f3-4ab9-9f65-f4a7c0887c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emergName</value>
      <webElementGuid>e23e6d4d-cbe4-48c9-8bde-15bc164769a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>23f60373-f138-4027-81c2-8e8687f6702b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emergName&quot;)</value>
      <webElementGuid>a336725f-5bf3-48b5-9f1d-c2d6127be849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emergName']</value>
      <webElementGuid>f4cfa557-ddef-408e-b9f5-cdc8f386df68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[5]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>633a56a3-2bf2-4bfd-8659-de0fb3dbcc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>1eafcd47-27c5-4e16-a8fd-a88891f82f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Full Name' and @type = 'text' and @id = 'emergName']</value>
      <webElementGuid>971dafc2-86fb-45b8-b258-5c45b3f05d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
