<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_QVX3552</name>
   <tag></tag>
   <elementGuidId>b34cffc0-13f1-4be8-aaa4-ac617ff02c00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.unit > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb5fc9f9-3db9-413e-b402-3cde18dbafdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QVX3552</value>
      <webElementGuid>257856f5-6e0e-413d-a4fc-0f19b1c1eb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_datatable_vertical_scroll&quot;)/tbody[1]/tr[@class=&quot;mainRow&quot;]/td[@class=&quot;unit&quot;]/span[1]</value>
      <webElementGuid>dca59da2-a660-4832-bf45-c59f28b887b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[4]/span</value>
      <webElementGuid>1e650e86-8ebd-4039-97ec-2d046a68f2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mob.iroomz@yopmail.com'])[1]/following::span[1]</value>
      <webElementGuid>89da20e2-e328-4557-8c61-ea2253b0e160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mo b'])[1]/following::span[4]</value>
      <webElementGuid>4f5644bb-d8c4-4dd7-9531-1faf8530009b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::span[2]</value>
      <webElementGuid>68e0bb76-72fe-494c-a8ba-69774f677b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::span[3]</value>
      <webElementGuid>a3f31db3-aae9-46f3-bc34-03b143ef76b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QVX3552']/parent::*</value>
      <webElementGuid>6fc2d6d5-814b-4ad4-ac61-488aee5147f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>5e25a781-f41f-4cb6-bad4-c022f2f369e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'QVX3552' or . = 'QVX3552')]</value>
      <webElementGuid>67350847-5998-4926-98a5-c147a0e159f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
