<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Type to search property unit  property _c7852a</name>
   <tag></tag>
   <elementGuidId>8dd2c653-1944-497e-bce5-f4433fcb500a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/div/div/form/div[1]/div/div/div/div/div[1]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-liki3c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5c72ae1-60ff-490a-aa93-8b41aa8dafcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-liki3c</value>
      <webElementGuid>8cb4e304-fe88-473b-8c25-91a0b1ad439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app_form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;css-b62m3t-container&quot;]/div[@class=&quot;css-r5vfb9-control&quot;]/div[@class=&quot;css-t6uyiw&quot;]/div[@class=&quot;css-liki3c&quot;]</value>
      <webElementGuid>88d23d09-9615-438c-bdf9-ef70d979c613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>36ecf1e7-c1de-433b-b065-039933138bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type to search property unit | property room | tenant'])[1]/following::div[1]</value>
      <webElementGuid>c47769cc-2e37-4e55-aee5-4dfa79880998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Name | Room Name | Tenant'])[1]/following::div[5]</value>
      <webElementGuid>bb06fb96-fab0-49fd-af30-5a91a1ca0eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Appointment Date'])[1]/preceding::div[2]</value>
      <webElementGuid>6cac429f-2b0b-4f41-a167-d0616dab72f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f53f581c-7872-402c-9d3a-cd540065f08e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
