<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RM_tasks.0.cost.labourFee</name>
   <tag></tag>
   <elementGuidId>4689f27b-779c-4994-b4ca-8da7012865e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tasks.0.cost.labourFee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b3946a9-2f58-4df5-8e9b-75b14dd484cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Labour Fee</value>
      <webElementGuid>28d974f2-2fbb-49e1-9561-6b8eab072592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27e961ec-560a-41b1-a27a-fff3bee02f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tasks.0.cost.labourFee</value>
      <webElementGuid>212afe46-bca4-4b85-bcfa-88d427f701b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>0594dc57-b13c-4324-9c82-8f0f61b18a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tasks.0.cost.labourFee&quot;)</value>
      <webElementGuid>ce1df6cd-67ca-4889-8e76-8e747928e371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tasks.0.cost.labourFee']</value>
      <webElementGuid>b7dcdfbf-6fa0-46f4-8d77-f90c5d4f809c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[11]/div[2]/div/div/div/input</value>
      <webElementGuid>6fd307f2-673c-4dc6-b6e0-fea6f8e7a248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>9e79f7cf-c678-4bd4-ba57-e5d415239182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Labour Fee' and @type = 'text' and @id = 'tasks.0.cost.labourFee']</value>
      <webElementGuid>bae82bba-68f8-4ad2-92f1-7852a4cb9b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
