<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ISB3105</name>
   <tag></tag>
   <elementGuidId>c6298acc-b381-4376-be88-982e8f2dd815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.unitName > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b83a29ad-02bf-474a-9775-c5bd6f4c884b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ISB3105</value>
      <webElementGuid>f55d44f5-239b-4c20-a2fb-1928e2336653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_datatable_vertical_scroll&quot;)/tbody[1]/tr[@class=&quot;mainRow&quot;]/td[@class=&quot;unitName&quot;]/span[1]</value>
      <webElementGuid>f19e9afd-e88e-41ce-8d9b-0a61ce56be1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[2]/span</value>
      <webElementGuid>d9cf0bd3-d1cf-4a45-b18d-21a76f55d137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::span[2]</value>
      <webElementGuid>70d9cae4-80bc-4cf8-be19-32bc24dc4849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::span[3]</value>
      <webElementGuid>5e8b1022-90fb-4555-afad-382a5c20bd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(GAY SARAN | 0173126058 | injectionunwitting@yopmail.com)'])[1]/preceding::span[2]</value>
      <webElementGuid>9b040a08-f1eb-4750-8bbd-493d18cc549c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iroomz'])[1]/preceding::span[4]</value>
      <webElementGuid>6c94ff7d-523d-491a-8768-027762209571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ISB3105']/parent::*</value>
      <webElementGuid>79024862-e285-4b70-8e9c-3f908629950c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>59c990de-3e21-49ac-bfcc-4802d9503163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ISB3105' or . = 'ISB3105')]</value>
      <webElementGuid>9e254061-80d4-4b34-a320-b3a508c68ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
