<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Upload New Attachment_at-input-upload</name>
   <tag></tag>
   <elementGuidId>4a4bd413-ddd1-41ff-a51b-c28169ec7581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.at-input-upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_modal_create_app']/div/div/div[3]/div/div[2]/section/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>adfe33d5-bb42-4733-959f-56345221a7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>at-input-upload</value>
      <webElementGuid>7f59710c-4a35-4904-939e-d11826b5daac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[3]/div[1]/div[@class=&quot;at-input&quot;]/section[1]/div[1]/div[@class=&quot;at-input-upload&quot;]</value>
      <webElementGuid>125fa6a7-849e-453c-9cd1-b6f6015a7967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_create_app']/div/div/div[3]/div/div[2]/section/div/div</value>
      <webElementGuid>0ca39106-7287-4a45-a593-8e5ca9a849a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>2437236d-9746-4769-87cc-57e06075c3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
