<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Upload New Attachment_at-input-upload</name>
   <tag></tag>
   <elementGuidId>4a4bd413-ddd1-41ff-a51b-c28169ec7581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[5]/div/div/div/div[3]/div/div[2]/section/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.at-input-upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76b31580-d7b3-4ede-a2e9-4db6f793917e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>at-input-upload</value>
      <webElementGuid>9b8d2a2a-3fa9-4748-9c9e-e11c12a1e57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_modal_create_app&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[3]/div[1]/div[@class=&quot;at-input&quot;]/section[1]/div[1]/div[@class=&quot;at-input-upload&quot;]</value>
      <webElementGuid>cd9758da-1e95-4a17-b9ca-38fa95d72418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_modal_create_app']/div/div/div[3]/div/div[2]/section/div/div</value>
      <webElementGuid>5d58dac1-8aac-4f65-9d5e-77d8a0c75aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div</value>
      <webElementGuid>8ffe5a11-9e62-4918-b9f0-c381d62e09ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
