<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NYY6870</name>
   <tag></tag>
   <elementGuidId>2eb600c5-b7c0-4fc5-873e-fba03d24b412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[5]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.unit > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78013046-7b04-4d2b-987d-12487701e857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NYY6870</value>
      <webElementGuid>ca1ca46c-655d-4403-81be-bda1b6a6f9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_datatable_vertical_scroll&quot;)/tbody[1]/tr[@class=&quot;mainRow&quot;]/td[@class=&quot;unit&quot;]/span[1]</value>
      <webElementGuid>7e41d528-07f6-49f8-9c06-fbb5620cf0cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[5]/span</value>
      <webElementGuid>4a12a5df-a1d9-4c40-8368-034191cb0f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vago Neue J0182333701lampsaucy@yopmail.com'])[1]/following::span[1]</value>
      <webElementGuid>bc3abb37-8103-46c1-b8e3-dc1c4ad9ef32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VAGO NEUE J'])[1]/following::span[2]</value>
      <webElementGuid>fb841f16-9b2b-4f3f-8eed-989f19448285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NYY6870_Room 1'])[1]/preceding::span[1]</value>
      <webElementGuid>e9b4cae9-c1fe-4e3f-9e68-bfb9beab3e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/preceding::span[2]</value>
      <webElementGuid>655dbb44-0f71-4af6-876e-858a6bafdfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NYY6870']/parent::*</value>
      <webElementGuid>d0eea893-1a56-43a3-bc4f-7de34f9d36e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span</value>
      <webElementGuid>8761fbd8-33e8-40b0-8c21-e48a58e7595a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'NYY6870' or . = 'NYY6870')]</value>
      <webElementGuid>4319dbcc-85c1-43e2-b883-1a17605fedb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
