<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1950.00Show More</name>
   <tag></tag>
   <elementGuidId>66a43769-23b6-4848-ade0-d67d28500c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/div[2]/div[2]/div[1]/div/div/div/div[3]/div/div/div[2]/table/tbody/tr[1]/td[11]/text()</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '1950.00Show More' or . = '1950.00Show More')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e516a1c6-6a2c-477b-992c-b19ed116c74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>909915b6-1b99-4d7c-ba0e-4e82a914c2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1950.00Show More</value>
      <webElementGuid>d3725a62-a33c-4dc6-a907-05c3302797f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-propertyPayoutReport&quot;]/div[@class=&quot;table-overflow&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;scrollable&quot;]/table[@id=&quot;kt_datatable_vertical_scroll&quot;]/tbody[@class=&quot;fw-normal fs-8 text-gray-800 pr-table-content&quot;]/tr[@class=&quot;pr-row-border&quot;]/td[8]</value>
      <webElementGuid>5eb11822-50eb-4b78-9bc7-901ec4a2ec6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[8]</value>
      <webElementGuid>c0fb534b-b027-4f93-83f1-71d8c35f16b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIERRE WINCHINTI'])[1]/following::td[5]</value>
      <webElementGuid>ee8a36e4-056e-402e-b4df-dc6d3f4e32fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UWR3551_Room 1'])[1]/following::td[6]</value>
      <webElementGuid>e859eb44-dc06-4d2b-ad71-ce4a51116e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[1]</value>
      <webElementGuid>eef95e70-13fd-4d8c-984d-f8addd0d42bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]</value>
      <webElementGuid>301b46e0-e51e-49bf-893d-164c7af8f72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1950.00Show More' or . = '1950.00Show More')]</value>
      <webElementGuid>93bc0c93-83f3-4f1b-ac97-e01f68c33958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
