<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1950.00Show More</name>
   <tag></tag>
   <elementGuidId>66a43769-23b6-4848-ade0-d67d28500c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>894f71de-4026-4a15-b9ee-80f20988fe84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6d52dcd4-27ec-41d6-b8b0-7103d3e5160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1950.00Show More</value>
      <webElementGuid>bd61b717-e55f-417d-aad4-ad2003efa051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/div[@class=&quot;page-propertyPayoutReport&quot;]/div[@class=&quot;table-overflow&quot;]/div[@class=&quot;infinite-scroll-component__outerdiv&quot;]/div[@class=&quot;infinite-scroll-component&quot;]/div[@class=&quot;scrollable&quot;]/table[@id=&quot;kt_datatable_vertical_scroll&quot;]/tbody[@class=&quot;fw-normal fs-8 text-gray-800 pr-table-content&quot;]/tr[@class=&quot;pr-row-border&quot;]/td[8]</value>
      <webElementGuid>54725f1c-069b-4061-be26-a64cdd5df764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[8]</value>
      <webElementGuid>78d536fc-cc8f-4b38-aa1f-823974599a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIERRE WINCHINTI'])[1]/following::td[5]</value>
      <webElementGuid>fa0ae2d1-e8be-4e1f-833c-6892ec0c0c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UWR3551_Room 1'])[1]/following::td[6]</value>
      <webElementGuid>14626a71-3035-408d-8f4b-24a72cacfa59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[1]</value>
      <webElementGuid>42ebbee9-72b1-4267-b96e-f5f659d55bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]</value>
      <webElementGuid>76cc162d-0d54-4ecc-b60f-e2e7160fd63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '1950.00Show More' or . = '1950.00Show More')]</value>
      <webElementGuid>1dc6646c-fcba-4e66-8513-ed0a8836c273</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
