<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RM_rental</name>
   <tag></tag>
   <elementGuidId>50f87463-4395-44b1-abdc-497fd5564e38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rental</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rental']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81e736a5-56b3-431d-a280-17a5b7e726dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rental Fee</value>
      <webElementGuid>29359b5d-4927-4432-95b3-bc06d24199df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d8fafe5-9c8e-49a4-9533-66cf80ceae41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rental</value>
      <webElementGuid>f0f2726c-881b-43b7-91f9-eea25f34c381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>0dabfd97-d9a3-466d-a654-509a36692758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rental&quot;)</value>
      <webElementGuid>2c858612-1c06-482f-a6e1-c70c16853d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rental']</value>
      <webElementGuid>1e9f5454-2f31-43e0-b4b1-c275088f88d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>f87a8dc8-1854-43af-b81a-60621aeee5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/input</value>
      <webElementGuid>5e3f1429-d4ab-45aa-84b3-6330812716da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Rental Fee' and @type = 'text' and @id = 'rental']</value>
      <webElementGuid>30f53c77-671b-404d-a9da-25605dc2755c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
