<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Viewable to Landlord_landlordView</name>
   <tag></tag>
   <elementGuidId>c18ef6b7-3717-4bdc-a666-8c46d252d7ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#landlordView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='landlordView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1283517-a073-4d6d-8ae8-42288f549aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>landlordView</value>
      <webElementGuid>bf71db31-af22-4dce-9a0f-7aa7b0061ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ec43d8b0-059b-458c-9eb6-16c8d9b763ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landlordView</value>
      <webElementGuid>28de70ac-619b-4a88-b8ad-2484cfd80fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7c1563db-fc40-4988-b7be-953729bb6ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landlordView&quot;)</value>
      <webElementGuid>35d98203-61e8-4803-98d6-f8d976ae6504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='landlordView']</value>
      <webElementGuid>0f60a0ab-9b9d-46ae-a20f-2ba18c94496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_modal_create_app_form']/div[3]/div/div[4]/div/div/div/input</value>
      <webElementGuid>a5745986-1350-49cd-afc9-ab0dfa76c8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>9212e7e3-e725-4008-b8f6-5a38f519fa6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'landlordView' and @type = 'checkbox' and @id = 'landlordView']</value>
      <webElementGuid>ba09a2f8-a19c-44d8-9af2-4b9bfaaa0483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
