<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ali</name>
   <tag></tag>
   <elementGuidId>c96ca315-438f-4a89-a9be-b1b7a2b594be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.landlord > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>22f521b4-9ac1-416e-b264-d0a7224a7e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ali</value>
      <webElementGuid>885348ff-4304-428e-9195-6d07495b09a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_datatable_vertical_scroll&quot;)/tbody[1]/tr[@class=&quot;mainRow&quot;]/td[@class=&quot;landlord&quot;]/span[1]</value>
      <webElementGuid>3c6585a2-d037-4bf2-8f00-e31bc5598c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='kt_datatable_vertical_scroll']/tbody/tr/td[2]/span</value>
      <webElementGuid>37930502-a014-4bdb-a583-e5cf4f8a4b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::span[1]</value>
      <webElementGuid>c9b89f9d-ed1c-4eb6-be14-69b29650469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agreement Details'])[1]/following::span[2]</value>
      <webElementGuid>c9a2eaa4-1ea0-4ce0-8199-c5c69064b968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='imali0926@yopmail.com'])[1]/preceding::span[3]</value>
      <webElementGuid>7d8a041c-4daa-499f-84d8-a9a7cfe83ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NYY6870'])[1]/preceding::span[4]</value>
      <webElementGuid>64ddb735-d415-41c6-9113-1e9a5f067ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ali']/parent::*</value>
      <webElementGuid>db07336d-f382-44f4-b44f-78791c71ce7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>575f9c8c-2bf4-4cd6-aa4b-479f87d098e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ali' or . = 'Ali')]</value>
      <webElementGuid>99a6d0aa-c65b-41f2-aecf-9eac31d77179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
